// @ts-nocheck
import * as T from 'three';
import {mergeGeometries} from 'three/examples/jsm/utils/BufferGeometryUtils.js';
const TAU=Math.PI*2;
function random(seed=91371){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
const height=(x,z)=>Math.sin(x*.065+1)*1.45+Math.sin(z*.085)*1.1+Math.sin(x*.15+z*.075)*.52+Math.cos(x*.29-z*.24)*.13;
const v=(x=0,y=0,z=0)=>new T.Vector3(x,y,z);
function leafGeometry(){const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute([0,0,0,-.24,.015,.22,-.36,.02,.46,-.25,.005,.74,0,-.025,1,.25,.005,.74,.36,.02,.46,.24,.015,.22,0,.075,.47],3));g.setAttribute('uv',new T.Float32BufferAttribute([.5,0,.16,.22,0,.46,.15,.74,.5,1,.85,.74,1,.46,.84,.22,.5,.47],2));const indices=[];for(let i=0;i<8;i++)indices.push(i,(i+1)%8,8);g.setIndex(indices);g.computeVertexNormals();return g;}
function tube(points,radii,sides=7){
 const pos=[],uv=[],ind=[];
 for(let i=0;i<points.length;i++){const dir=points[Math.min(i+1,points.length-1)].clone().sub(points[Math.max(0,i-1)]).normalize();const a=v(1,0,0);if(Math.abs(dir.x)>.9)a.set(0,0,1);a.cross(dir).normalize();const b=dir.clone().cross(a).normalize();for(let j=0;j<=sides;j++){const th=j/sides*TAU;const q=points[i].clone().addScaledVector(a,Math.cos(th)*radii[i]).addScaledVector(b,Math.sin(th)*radii[i]);pos.push(q.x,q.y,q.z);uv.push(j/sides,i*.5);if(i<points.length-1&&j<sides){const k=i*(sides+1)+j;ind.push(k,k+1,k+sides+1,k+1,k+sides+2,k+sides+1);}}}
 const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(pos,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(ind);g.computeVertexNormals();return g;
}
export function createForest(host,onReady){
 const rand=random();const r=(a=0,b=1)=>a+(b-a)*rand();
 const scene=new T.Scene();scene.background=new T.Color('#889e96');scene.fog=new T.FogExp2('#748f84',.0145);
 const camera=new T.PerspectiveCamera(62,innerWidth/innerHeight,.08,220);camera.position.set(0,height(0,16)+1.85,16);camera.rotation.order='YXZ';camera.rotation.x=.045;
 const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;host.appendChild(renderer.domElement);renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','Explore com WASD. Arraste para olhar. Q e E mudam a altura.');
 scene.add(new T.HemisphereLight('#b4d1d0','#242b17',.8));const sun=new T.DirectionalLight('#ffe6b2',3.9);sun.position.set(24,38,-32);sun.castShadow=true;sun.shadow.mapSize.set(4096,4096);Object.assign(sun.shadow.camera,{left:-36,right:36,top:36,bottom:-36,near:1,far:105});sun.shadow.bias=-.00012;sun.shadow.normalBias=.035;scene.add(sun);
 const uniforms=[];let time=0;
 function wind(material,amount){material.onBeforeCompile=shader=>{shader.uniforms.uTime={value:0};uniforms.push(shader.uniforms.uTime);shader.vertexShader='uniform float uTime;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>',`#include <begin_vertex>\nvec3 wp = (modelMatrix * instanceMatrix * vec4(position, 1.0)).xyz;\nfloat sw = sin(uTime*1.1 + wp.x*.24 + wp.z*.31) + .45*sin(uTime*2.0+wp.z*.7);\ntransformed.x += sw * ${amount.toFixed(3)} * position.z;\ntransformed.y += sin(uTime+wp.x*.4)*${(amount*.2).toFixed(3)}*position.z;`);};return material;}
 const loader=new T.TextureLoader();const textures=[];function texture(url,repeat){const t=loader.load(url);t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(repeat,repeat);t.colorSpace=T.SRGBColorSpace;t.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());textures.push(t);return t;}
 const soil=texture('/textures/ground.png',72),bark=texture('/textures/bark.png',1);
 const groundMat=new T.MeshStandardMaterial({color:'#9b9e81',map:soil,bumpMap:soil,bumpScale:.055,roughness:1,vertexColors:true});const terrain=new T.PlaneGeometry(240,240,260,260);terrain.rotateX(-Math.PI/2);const tp=terrain.attributes.position,colors=[];
 for(let i=0;i<tp.count;i++){const x=tp.getX(i),z=tp.getZ(i);tp.setY(i,height(x,z));const c=new T.Color().setHSL(.17+.04*Math.sin(x*.1+z*.2),.18,.43+.1*Math.sin(x*.21)*Math.cos(z*.17));colors.push(c.r,c.g,c.b);}terrain.setAttribute('color',new T.Float32BufferAttribute(colors,3));terrain.computeVertexNormals();const ground=new T.Mesh(terrain,groundMat);ground.receiveShadow=true;scene.add(ground);
 const barkMat=new T.MeshStandardMaterial({color:'#c2b8a2',map:bark,bumpMap:bark,bumpScale:.09,roughness:1});const foliageMat=wind(new T.MeshStandardMaterial({color:'#c6d29a',roughness:.94,side:T.DoubleSide}),.085);const leaves=[],trees=[];
 function branch(start,dir,len,rad,depth,out){
  const pts=[start.clone()];let p=start.clone();const bend=v(r(-1,1),depth>0?r(.15,.5):0,r(-1,1)).multiplyScalar(len*.035);
  for(let k=1;k<=6;k++){p=p.clone().addScaledVector(dir,len/6).addScaledVector(bend,k/6);pts.push(p);}
  out.push(tube(pts,[rad*1.16,rad,rad*.87,rad*.72,rad*.54,rad*.35,rad*.1],depth===0?12:7));
  if(depth<3){const children=depth===0?9:3;for(let j=0;j<children;j++){const f=depth===0?r(.45,.97):r(.48,1),base=pts[Math.min(6,Math.floor(f*6))],a=r(0,TAU);const nd=depth===0?v(Math.cos(a)*.95,r(.15,.65),Math.sin(a)*.95).normalize():dir.clone().multiplyScalar(.7).add(v(Math.cos(a)*.8,r(.05,.65),Math.sin(a)*.8)).normalize();branch(base,nd,len*(depth===0?r(.3,.5):r(.48,.72)),rad*(depth===0?.4:.42),depth+1,out);}}
  else{for(let n=0;n<30;n++){const f=r(.05,1),q=start.clone().lerp(p,f).add(v(r(-.42,.42),r(-.18,.32),r(-.42,.42)));leaves.push({p:q,s:r(.13,.26),a:r(0,TAU)});}}
 }
 for(let i=0;i<172;i++){let x=r(-76,76),z=r(-90,70);if(i<9){const placements=[[-6,12],[5,7],[-9,-3],[9,-10],[-3,-16],[14,18],[-14,22],[4,-28],[-18,-26]];[x,z]=placements[i];}else if(Math.hypot(x,z-10)<6)x+=x<0?-7:7;const y=height(x,z),h=i<9?r(13,19):r(8,21),rad=i<9?r(.48,.82):r(.2,.64);trees.push({x,z,y,rad,h});const out=[];branch(v(x,y-.2,z),v(r(-.08,.08),1,r(-.08,.08)).normalize(),h,rad,0,out);
  for(let k=0;k<7;k++){const a=k/7*TAU+r(-.2,.2),len=rad*r(3,6),end=v(x+Math.cos(a)*len,height(x+Math.cos(a)*len,z+Math.sin(a)*len)+.025,z+Math.sin(a)*len);out.push(tube([v(x,y+.6,z),v(x+Math.cos(a)*rad*1.2,y+.13,z+Math.sin(a)*rad*1.2),end],[rad*.45,rad*.26,.015],7));}
  const mesh=new T.Mesh(mergeGeometries(out),barkMat);out.forEach(g=>g.dispose());mesh.castShadow=true;mesh.receiveShadow=true;scene.add(mesh);}
 const leafMesh=new T.InstancedMesh(leafGeometry(),foliageMat,leaves.length),obj=new T.Object3D(),col=new T.Color();leaves.forEach((e,i)=>{obj.position.copy(e.p);obj.rotation.set(r(-.8,.8),e.a,r(-.5,.5));obj.scale.set(e.s,e.s,e.s*r(1,1.65));obj.updateMatrix();leafMesh.setMatrixAt(i,obj.matrix);col.setHSL(r(.19,.29),r(.28,.5),r(.12,.3));leafMesh.setColorAt(i,col);});leafMesh.castShadow=true;leafMesh.receiveShadow=true;scene.add(leafMesh);
 const blade=new T.BufferGeometry(),bp=[],bi=[],bc=[];for(let k=0;k<6;k++){const t=k/5,w=.014*(1-t)+.0005;bp.push(-w,t*.62,t*t*.26,w,t*.62,t*t*.26);for(let j=0;j<2;j++)bc.push(.38+t*.62,.38+t*.62,.38+t*.62);if(k<5){const a=k*2;bi.push(a,a+1,a+2,a+1,a+3,a+2);}}blade.setAttribute('position',new T.Float32BufferAttribute(bp,3));blade.setAttribute('color',new T.Float32BufferAttribute(bc,3));blade.setIndex(bi);blade.computeVertexNormals();const grassMat=wind(new T.MeshStandardMaterial({color:'#a9b576',vertexColors:true,side:T.DoubleSide,roughness:1}),.15),grass=new T.InstancedMesh(blade,grassMat,270000);
 for(let i=0;i<grass.count;i++){const near=i<200000,extent=near?35:78,x=r(-extent,extent),z=r(-extent,extent)+5;obj.position.set(x,height(x,z)-.02,z);obj.rotation.set(0,r(0,TAU),r(-.22,.22));const s=r(.3,1.05)*(1+.4*Math.sin(x*.65)*Math.sin(z*.63));obj.scale.set(r(.65,1.2),s,s);obj.updateMatrix();grass.setMatrixAt(i,obj.matrix);col.setHSL(r(.18,.26),r(.3,.54),r(.16,.34));grass.setColorAt(i,col);}grass.receiveShadow=true;scene.add(grass);
 // The understory is made from curved surfaces, with individual leaflets rather than alpha cards.
 function instances(geometry,material,count,place,shadow=false){const m=new T.InstancedMesh(geometry,material,count);for(let i=0;i<count;i++){obj.position.set(0,0,0);obj.rotation.set(0,0,0);obj.scale.setScalar(1);col.set('#ffffff');place(i,obj,col);obj.updateMatrix();m.setMatrixAt(i,obj.matrix);m.setColorAt(i,col);}m.castShadow=shadow;m.receiveShadow=true;scene.add(m);return m;}
 function fernGeometry(seed){const fr=random(seed),parts=[];for(let j=0;j<8;j++){const az=j/8*TAU+fr()*.35,len=.75+fr()*.7,lift=.35+fr()*.3;const stem=[];for(let k=0;k<8;k++){const f=k/7;stem.push(v(Math.sin(az)*len*f,.08+Math.sin(f*Math.PI*.87)*lift,Math.cos(az)*len*f));}parts.push(tube(stem,stem.map((_,k)=>.008*(1-k/8)),4).deleteAttribute('uv'));
  for(let k=1;k<18;k++){const f=k/18,span=(.06+.26*Math.pow(Math.sin(f*Math.PI),.7))*(1-f*.4);for(const side of[-1,1]){const g=leafGeometry().deleteAttribute('uv');obj.position.set(Math.sin(az)*len*f,.08+Math.sin(f*Math.PI*.87)*lift,Math.cos(az)*len*f);obj.rotation.set(.12*Math.sin(f*4),az+side*(1.07+f*.35),side*.1);obj.scale.set(span*.55,span,span);obj.updateMatrix();g.applyMatrix4(obj.matrix);parts.push(g);}}}
  const g=mergeGeometries(parts);parts.forEach(p=>p.dispose());return g;}
 const fernMat=wind(new T.MeshStandardMaterial({color:'#88aa62',side:T.DoubleSide,roughness:.88}),.035);
 for(let variant=0;variant<3;variant++)instances(fernGeometry(132+variant*17),fernMat,160,(i,o,c)=>{let x=r(-46,46),z=r(-48,40);if(i<4){x=[-2.5,2.2,-4.1,3.9][i]+variant*.15;z=[14,11,6,-2][i]+variant*.6;}o.position.set(x,height(x,z),z);o.rotation.y=r(0,TAU);o.scale.setScalar(r(.65,1.35));c.setHSL(r(.23,.3),r(.35,.55),r(.25,.45));},true);
 const shrubData=[];for(let i=0;i<530;i++){let x=r(-66,66),z=r(-74,58),size=r(.35,1.1);if(i<15){x=r(-9,9);z=r(-5,20);}for(let j=0;j<65;j++){const az=r(0,TAU),d=Math.sqrt(rand())*size,y=height(x,z)+.08+Math.sqrt(Math.max(0,1-d*d/(size*size)))*size*r(.4,1.5);shrubData.push({x:x+Math.sin(az)*d,y,z:z+Math.cos(az)*d,s:r(.12,.25),az});}}
 instances(leafGeometry(),foliageMat,shrubData.length,(i,o,c)=>{const p=shrubData[i];o.position.set(p.x,p.y,p.z);o.rotation.set(r(-.5,.7),p.az,r(-.6,.6));o.scale.set(p.s,p.s,p.s*r(1.3,2));c.setHSL(r(.22,.3),r(.3,.55),r(.12,.32));},true);
 const mossMat=new T.MeshStandardMaterial({color:'#647843',roughness:1});
 const rockGeo=new T.IcosahedronGeometry(1,2);const rp=rockGeo.attributes.position;for(let i=0;i<rp.count;i++){const x=rp.getX(i),y=rp.getY(i),z=rp.getZ(i),q=1+.12*Math.sin(x*8+z*6)*Math.sin(y*9-z*4);rp.setXYZ(i,x*q,y*q,z*q);}rockGeo.computeVertexNormals();
 const rockMat=new T.MeshStandardMaterial({color:'#69716a',roughness:1});rockMat.onBeforeCompile=s=>{s.vertexShader=s.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 vRockPosition;').replace('#include <begin_vertex>','#include <begin_vertex>\nvRockPosition=position;');s.fragmentShader=s.fragmentShader.replace('#include <common>','#include <common>\nvarying vec3 vRockPosition;').replace('#include <color_fragment>',`#include <color_fragment>\nfloat grain=sin(vRockPosition.x*67.)*sin(vRockPosition.y*92.+vRockPosition.z*87.);\nfloat moss=smoothstep(.05,.45,vRockPosition.y+.16*sin(vRockPosition.x*14.)*sin(vRockPosition.z*16.));\ndiffuseColor.rgb*=.78+grain*.19;diffuseColor.rgb=mix(diffuseColor.rgb,diffuseColor.rgb*vec3(.65,.96,.37),moss*.85);`);};
 const rocks=[];instances(rockGeo,rockMat,480,(i,o,c)=>{let x=r(-64,64),z=r(-64,58),s=r(.08,.55);if(i<8){x=[3.1,3.8,4.4,-4,-5,-6,1,-1][i];z=[9,9.3,9.1,3,2.8,3,20,-14][i];s=r(.5,1.15);}o.position.set(x,height(x,z)+s*.14,z);o.rotation.set(r(-.3,.3),r(0,TAU),r(-.2,.2));o.scale.set(s*r(1,1.5),s*.65,s);c.setHSL(.15,.04,r(.45,.8));rocks.push({x,z,s});},true);
 // Fallen trunks and broken limbs have textured bark, end-grain and ground contact.
 const woodMat=new T.MeshStandardMaterial({color:'#9e8156',roughness:1});woodMat.onBeforeCompile=s=>{s.fragmentShader=s.fragmentShader.replace('#include <color_fragment>',`#include <color_fragment>\nfloat rings=sin(length(vUv-.5)*170.);diffuseColor.rgb*=.8+.15*rings;`);s.defines.USE_UV='';};
 for(let i=0;i<28;i++){let x=r(-48,48),z=r(-52,42);if(i===0){x=-3.2;z=5;}const a=i===0?1.1:r(0,TAU),len=i===0?6:r(1.5,5),rad=r(.12,.34),start=v(x,height(x,z)+rad*.65,z),end=v(x+Math.cos(a)*len,0,z+Math.sin(a)*len);end.y=height(end.x,end.z)+rad*.55;const mid=start.clone().lerp(end,.5).add(v(0,.05,0));const log=new T.Mesh(tube([start,mid,end],[rad,rad*.92,rad*.75],11),barkMat);log.castShadow=true;log.receiveShadow=true;scene.add(log);const cap=new T.Mesh(new T.CircleGeometry(rad*.72,18),woodMat);cap.position.copy(end);cap.quaternion.setFromUnitVectors(v(0,0,1),end.clone().sub(start).normalize());scene.add(cap);for(let k=0;k<3;k++){const p=start.clone().lerp(end,r(.2,.8));const twig=new T.Mesh(tube([p,p.clone().add(v(r(-.7,.7),r(.15,.5),r(-.7,.7)))],[rad*.2,.008],5),barkMat);twig.castShadow=true;scene.add(twig);}}
 const litterMat=new T.MeshStandardMaterial({color:'#ab9468',roughness:1,side:T.DoubleSide});instances(leafGeometry(),litterMat,18000,(i,o,c)=>{const x=r(-44,44),z=r(-48,42);o.position.set(x,height(x,z)+.025,z);o.rotation.set(r(-.1,.1),r(0,TAU),r(-.12,.12));const s=r(.06,.22);o.scale.set(s,s,s*1.3);c.setHSL(r(.07,.17),r(.2,.5),r(.1,.3));});
 instances(new T.IcosahedronGeometry(1,1),mossMat,4200,(i,o,c)=>{const tree=trees[i%trees.length],a=r(0,TAU),d=tree.rad*r(1,3.1),x=tree.x+Math.cos(a)*d,z=tree.z+Math.sin(a)*d,s=r(.04,.19);o.position.set(x,height(x,z)+s*.1,z);o.scale.set(s,s*.25,s*.8);c.setHSL(r(.18,.28),.44,r(.3,.55));});
 const stemMat=new T.MeshStandardMaterial({color:'#526640',roughness:1});const stemGeo=new T.CylinderGeometry(.006,.011,.65,4);stemGeo.translate(0,.325,0);const flowerLocations=[];
 instances(stemGeo,stemMat,370,(i,o,c)=>{const cluster=i%18,cr=random(cluster+993),x=(cr()-.5)*60+r(-1.6,1.6),z=(cr()-.5)*64+r(-1.6,1.6),s=r(.45,1.15);o.position.set(x,height(x,z),z);o.scale.setScalar(s);flowerLocations.push(v(x,height(x,z)+.64*s,z));});
 const petals=new T.SphereGeometry(1,5,3),petalMat=new T.MeshStandardMaterial({color:'#eee7c9',roughness:.9});instances(petals,petalMat,flowerLocations.length*6,(i,o,c)=>{const p=flowerLocations[Math.floor(i/6)],a=i%6/6*TAU;o.position.copy(p).add(v(Math.sin(a)*.036,0,Math.cos(a)*.036));o.rotation.y=a;o.scale.set(.018,.009,.034);c.setHSL(.12,.12,r(.6,.88));});instances(new T.SphereGeometry(1,6,4),new T.MeshStandardMaterial({color:'#bea340',roughness:1}),flowerLocations.length,(i,o)=>{o.position.copy(flowerLocations[i]).add(v(0,.012,0));o.scale.set(.018,.012,.018);});
 const mushroomCap=new T.SphereGeometry(1,9,5,0,TAU,0,Math.PI*.62),mushroomMat=new T.MeshStandardMaterial({color:'#ac6940',roughness:.95});instances(mushroomCap,mushroomMat,130,(i,o,c)=>{const tree=trees[i%30],x=tree.x+r(-1.2,1.2),z=tree.z+r(-1.2,1.2),s=r(.045,.13);o.position.set(x,height(x,z)+s*.8,z);o.rotation.set(r(-.2,.2),0,r(-.2,.2));o.scale.set(s,s*.55,s);c.setHSL(r(.055,.12),.33,r(.4,.65));});
 // Warm shafts hang between the canopy gaps. Soft noise removes visible cone boundaries.
 const rayMat=new T.ShaderMaterial({transparent:true,depthWrite:false,side:T.DoubleSide,blending:T.AdditiveBlending,uniforms:{uTime:{value:0}},vertexShader:`varying vec3 p;varying vec3 w;void main(){p=position;w=(modelMatrix*vec4(position,1.)).xyz;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying vec3 p;varying vec3 w;uniform float uTime;void main(){float edge=pow(max(0.,1.-length(p.xz)),2.);float ends=smoothstep(-.5,-.25,p.y)*(1.-smoothstep(.28,.5,p.y));float n=.72+.28*sin(w.y*.63+w.x*.32+uTime*.09);float alpha=edge*ends*n*.034;gl_FragColor=vec4(.95,.86,.60,alpha);}`});uniforms.push(rayMat.uniforms.uTime);
 for(let i=0;i<13;i++){const end=v(r(-17,18),1,r(-30,10)),start=end.clone().add(v(11,26,-16)),dir=start.clone().sub(end),ray=new T.Mesh(new T.CylinderGeometry(.22,1.1,1,24,1,true),rayMat);ray.position.copy(start.clone().lerp(end,.5));ray.scale.set(r(.5,1.2),dir.length(),r(.5,1.2));ray.quaternion.setFromUnitVectors(v(0,1,0),dir.normalize());scene.add(ray);}
 const motesGeo=new T.BufferGeometry(),motes=[];for(let i=0;i<520;i++)motes.push(r(-30,30),r(1,16),r(-35,30));motesGeo.setAttribute('position',new T.Float32BufferAttribute(motes,3));const motesMat=new T.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{uTime:{value:0}},vertexShader:`uniform float uTime;varying float a;void main(){vec3 q=position;q.x+=sin(uTime*.19+position.y)*.7;q.y+=sin(uTime*.3+position.x)*.35;vec4 mv=modelViewMatrix*vec4(q,1.);gl_Position=projectionMatrix*mv;gl_PointSize=min(3.,35./-mv.z);a=.18+.3*pow(max(0.,sin(position.x+uTime*.5)),4.);}`,fragmentShader:`varying float a;void main(){float d=length(gl_PointCoord-.5)*2.;gl_FragColor=vec4(.94,.91,.7,(1.-smoothstep(.15,1.,d))*a);}`});uniforms.push(motesMat.uniforms.uTime);scene.add(new T.Points(motesGeo,motesMat));
 renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=true;
 const keys=new Set(),velocity=v();let dragging=false,lastX=0,lastY=0,yaw=0,pitch=.045;
 const down=e=>{if(e.target===renderer.domElement){dragging=true;lastX=e.clientX;lastY=e.clientY;renderer.domElement.setPointerCapture(e.pointerId);renderer.domElement.focus();}};const move=e=>{if(!dragging)return;yaw-=(e.clientX-lastX)*.0026;pitch-=(e.clientY-lastY)*.0026;pitch=T.MathUtils.clamp(pitch,-1.4,1.4);lastX=e.clientX;lastY=e.clientY;};const up=()=>dragging=false;
 const kd=e=>{if(['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ShiftLeft','ShiftRight'].includes(e.code)){e.preventDefault();keys.add(e.code);}};const ku=e=>keys.delete(e.code),blur=()=>{keys.clear();dragging=false;};renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',up);window.addEventListener('keydown',kd);window.addEventListener('keyup',ku);window.addEventListener('blur',blur);
 const resize=()=>{camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight);};window.addEventListener('resize',resize);
 let frame=0,last=performance.now();const animate=()=>{frame=requestAnimationFrame(animate);const now=performance.now(),dt=Math.min((now-last)/1000,.05);last=now;time+=dt;uniforms.forEach(u=>u.value=time);const input=v(Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft')),Number(keys.has('KeyE'))-Number(keys.has('KeyQ')),Number(keys.has('KeyS')||keys.has('ArrowDown'))-Number(keys.has('KeyW')||keys.has('ArrowUp')));input.normalize().applyAxisAngle(v(0,1,0),yaw).multiplyScalar(keys.has('ShiftLeft')?8:3.3);velocity.lerp(input,1-Math.exp(-dt*7));camera.position.addScaledVector(velocity,dt);camera.position.y=Math.max(height(camera.position.x,camera.position.z)+.4,camera.position.y);camera.position.x=T.MathUtils.clamp(camera.position.x,-90,90);camera.position.z=T.MathUtils.clamp(camera.position.z,-90,90);camera.rotation.set(pitch,yaw,0);renderer.render(scene,camera);};animate();onReady();
 return()=>{cancelAnimationFrame(frame);window.removeEventListener('keydown',kd);window.removeEventListener('keyup',ku);window.removeEventListener('blur',blur);window.removeEventListener('resize',resize);scene.traverse(o=>{o.geometry?.dispose();if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose());});renderer.dispose();renderer.domElement.remove();};
}
